disabled_rules:

opt_in_rules:
  - empty_count

included:
  - iOS
  - macOS
  - Shared

excluded:
  - iOSFrameworkTests
  - macOSFrameworkTests

force_cast:
  severity: warning

force_try:
  severity: warning

# Xcode guidepost at 120 but do not warn until 140 and error at 240
line_length:
  warning: 140
  error: 240
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1000
  error: 2000

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey

reporter:
  "xcode"
